# Generated by Django 4.1.7 on 2023-03-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_customermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='phoneNo',
            field=models.BigIntegerField(),
        ),
    ]
